### ISSUE TITLE
[Create Environment] Add GCP CSPM integration to the cloud testing flow

### ISSUE THREAD

**Issue by gurevichdmitry** [elastic/cloudbeat#1273]
**Motivation**
The motivation behind this task is to enhance our cloud testing environment by integrating GCP CSPM. In this task, we will add a new CSPM GCP integration to our testing environment. 

**Task Description**
- Create New Agent Policy for CSPM GCP: Create a new elastic agent policy for the GCP environment.

- Create a package policy CSPM GCP integration: Assign this package policy to the agent policy.

- Generate input data for Deployment Manager:
    ```
    DEPLOYMENT_NAME="<Unique stack name>" # john-qa-bc2-8-9-0-May28
    FLEET_URL="<Elastic Agent Fleet URL>"
    ENROLLMENT_TOKEN="<Elastic Agent Enrollment Token>"
    ELASTIC_ARTIFACT_SERVER="https://artifacts.elastic.co/downloads/beats/elastic-agent" # Replace artifact URL with a pre-release version (BC or snapshot)
    ELASTIC_AGENT_VERSION="<Elastic Agent Version>" # e.g: 8.8.0 | 8.8.0-SNAPSHOT
    ZONE="<GCP Zone>" # e.g: us-central1-a
    ALLOW_SSH=false # Set to true to allow SSH connections to the deployed instance
    ```
- Implement new Githhub actions in test-environment workflow: Modify the test-environment GitHub Workflow to include new actions for:
    - Installing the CSPM GCP integration.
    - Deploying the CSPM agent using the deployment manager.
 
- Add Sanity Tests for Findings Retrieval: Develop sanity basic tests to verify the proper functioning of the CSPM GCP integration.
These tests will focus on retrieval and validation of findings by type.

**Definition of done**
What needs to be completed at the end of this task
- [x] A new agent policy for CSPM GCP is created and configured.
- [x] A package policy is created and assigned to the agent policy.
- [x] A data for the deployment manager is successfully generated.
- [x] The test-environment GitHub Workflow is updated to include integration and agent deployment.
- [ ] Sanity tests for findings retrieval are implemented and pass successfully.

**Out of scope**
In-depth configuration of CSPM GCP integration options and settings (this may be addressed in separate tasks).
Extended verification of CSPM GCP by integration and functional tests.

**Related tasks/epics**
Reference related issues and epics
