### ISSUE TITLE
[CIS Azure][Meta] Integration changes

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1277]
**Motivation**
We've already have the boilerplate for Azure benchmark inside the integration.
We just need to make sure that we do the following changes:
- [ ] Update the findings index mapping (if we decide to add something custom)
- [ ] Insert link for the deployment template (that will be pushed into GitHub or S3 via `cloudbeat` workflow)
- [ ] Insert manual credentials configuration fields into the `azure.yml.hbs`
- [ ] Decide on how we handle the Azure subscription_id (if we need this as field in `hbs` or not)

**Definition of done**
What needs to be completed at the end of this task
- [ ] The above bullets

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics
