### ISSUE TITLE
[CIS Azure][META] ARM template changes

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1282]
**Motivation**
There are some gaps in the ARM template in the initial implementation.
Here is the list of topics:
- [x] Secure the VM (current we use static credentials instead of SSH keys or maybe eliminate the option at all)
- [x] VM exposes public IP for us to be able to connect to it (maybe eliminate at all)
- [x] The template doesn't install an agent yet (need to implement base64 script or pull script from remote link)
- [x] We do not use the deployment parameters yet
- [x] There is no uniqueness for resource names and they should be unique
- [ ] Consider different machine types and OS type
- [ ] Maybe have different templates for manual and assume role deployment because in order to assume role we need to expose ports and run services which are not needed when using manual credentials
- [x] Make sure that the built-in system role is enough and we do not need anything extra or less
- [x] Support multiple subscriptions and management groups (credentials and assume role change accordingly)
- [x] Maybe add the subscription as a parameter and propagate it to `cloudbeat` as well

**Definition of done**
What needs to be completed at the end of this task
- [x] The template should be secure
- [x] The template should support multiple subscriptions and management groups

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics

**Comment by oren-zohar** [comment]
@jeniawhite let's split these tasks into tickets when you come back 🙏

**Comment by orestisfl** [comment]
Closing for now
