### ISSUE TITLE
[CIS Azure][META] Support Azure authentication methods

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1291]
**Motivation**
In Azure, several [authentication methods](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#credential-types) are available to ensure secure access to resources.

We'll focus on manual and automatic authentication methods:
- [Manual](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#environment-variables)
- [Automatic](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#managed-identity)

The following options are for manual credentials:
- [Service principal with client secret](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#hdr-Service_principal_with_client_secret)
- [Service principal with certificate](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#hdr-Service_principal_with_certificate)
- [User with username and password](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#hdr-User_with_username_and_password)

The following options are for automatic credentials:
- Workload Identity
- Managed Identity

Since our scanner is being deployed inside Azure VM, so I think that we should utilize the `Managed Identity` option.
In `Managed Identity` you can either create custom identities or built-in system identities.
In order to avoid creating more resources we can utilize a system identity that allows us to carry out all of our queries and flows.

**Definition of done**
What needs to be completed at the end of this task
- [ ] The integration's UI and `hbs` manifests support new auth methods according to mocks
- [ ] Agent's config is updated to support new auth methods
- [ ] Cloudbeat uses agent config to fetch resources using the mentioned auth methods

**Out of scope**
What should not be included in this task

**Related tasks/epics**
Reference related issues and epics
- #1289 
- #1292
