### ISSUE TITLE
[Milestone 1] Measure effort to support non-default fleet namespaces

### ISSUE THREAD

**Issue by opauloh** [elastic/cloudbeat#2229]
**Motivation**

As stated by https://github.com/elastic/security-team/issues/9558, we want to start supporting Kibana Spaces, and for that, we understood that namespaces support should be implemented first.

As the decision to not support other namespaces than default was intentional, this ticket aims to gather the requirements needed to support non-default namespaces in cloudbeat.

**Definition of done**

- [ ] Gather requirements needed to support non-default namespace in cloudbeat
- [ ] It should consider findings and vulnerabilities
- [ ] Create follow-up tickets for implementation

**Out of scope**

- Implementation will be done in separate ticket(s)

**Related tasks/epics**

- https://github.com/elastic/security-team/issues/8759
- https://github.com/elastic/security-team/issues/9558
- https://github.com/elastic/sdh-beats/issues/3487

**Comment by oren-zohar** [comment]
This should be pretty straightforward, including mainly taking the namespace suffix into account when determining the findings datastream name, which is currently [hard-coded](https://github.com/elastic/cloudbeat/blob/d4812c8710ef67045840df553bc8a03a950ba34f/internal/config/config.go#L40)

I opened implementation task: 
- https://github.com/elastic/cloudbeat/issues/2289
