### ISSUE TITLE
Add CIS Rule number as a separate field to our events

### ISSUE THREAD

**Issue by oren-zohar** [elastic/cloudbeat#552]
### Background
We want to send the CIS rule number as a field instead of a tag.

### Definition of done
**Phase 1:**
- [x] Add the CIS rule number to the rule metadata (csp-policies) - https://github.com/elastic/csp-security-policies/pull/160
- [x] Add CIS rule number to our events - https://github.com/elastic/cloudbeat/pull/616
- [x] Add mapping to the integration (`keyword`) - https://github.com/elastic/integrations/pull/4920
- [x] Update technical index - https://github.com/elastic/security-team/pull/5705

**Phase 2:**
- [ ] Remove the CIS rule number from the tags field on the rego side
- [x] Open relevant tickets for Kibana after syncing with @kfirpeled (https://github.com/elastic/kibana/issues/146591)

**out of scope**
- Phase 2
- Anything related to Kibana, if there's something to follow up

**Comment by kfirpeled** [comment]
> * [ ]  Remove the CIS rule number from the tags field on the rego side

Wouldn't that be considered a breaking change?

cc: @eyalkraft

**Comment by eyalkraft** [comment]
It is breaking since I think Kibana has/had some logic for showing this number from the tags,
But as you know Kibana/ES never works with Newer agents, only equal or older.
So we can have that change introduced with BC in Kibana alone.

**Comment by kfirpeled** [comment]
I can suggest having an ingest pipeline to fix incoming data (calculate it from the tags) - so it will take one iteration of cloudbeat until the rule numbers will be available
wdyt?

**Comment by eyalkraft** [comment]
@kfirpeled sound legit, although I'm not sure if it'll be required since the work required to do in cloudbeat to implement this changes is rather small.

**Comment by oren-zohar** [comment]
@eyalkraft @kfirpeled so which one is it? it will be very easy to implement on cloudbeat side, and keep both fields as a first step, should we go in that direction?

**Comment by oren-zohar** [comment]
**Update**
I was considering two options, the first one is to enrich the event in cloudbeat which sounds like the most straightforward approach. I'll need to extract the rule number from the `tags` list. This seems error-prone if I'll be counting on the index, or even using some regex pattern. The second option is adding the field directly into our bundle which will make it much safer going forward, so I'm going with that option for now. 

In any case, the tags field will be kept for backward compatibility.

**Comment by oren-zohar** [comment]
verified


![Image](https://user-images.githubusercontent.com/85433724/218482400-20db7f72-f244-43db-a922-ca996884b96f.png)
