### ISSUE TITLE
[META] Support GCP Authentication methods

### ISSUE THREAD

**Issue by uri-weisman** [elastic/cloudbeat#764]
In GCP, several [authentication methods](https://cloud.google.com/docs/authentication?_ga=2.133039369.-680888746.1675691556&_gac=1.182932052.1676454762.Cj0KCQiAorKfBhC0ARIsAHDzsltyEl0yGobdGxZKz_Lja8wNS89Fl_tHR8HD_rQBu-ZXuvg6QnhI8CMaAn0gEALw_wcB) are available to ensure secure access to resources. 
For our use case, we'll focus on two authentication methods that use service accounts to enable services to access GCP resources without user intervention:

-  **OAuth2** ([server to server](https://developers.google.com/identity/protocols/oauth2/service-account)) - involves using a service account private key, which is a JSON file containing the service account's credentials, to obtain an access token.
-  **IAM role** - allows users to create custom IAM roles and assign them to service accounts for more granular control over resource access.

Both authentication methods can be provided with credentials through two options:
1. **Credentials file path** - the user provides a path to a JSON file containing authentication credentials. The agent should have read-only privileges to this file.
2. **Credentials JSON** - the user provides a JSON blob containing authentication credentials, which is transferred to cloudbeat through the agent policy.

In case the previously mentioned authentication methods are not valid or do not exist, the fallback option is to use Application Default Credentials ([ADC](https://cloud.google.com/docs/authentication/application-default-credentials)), GCP SDK for Go support it.

**Definition of done**
What needs to be completed at the end of this task
- [ ] The integration's UI supports new auth methods according to mocks.
- [ ] Agent's config is updated to support new auth methods.
- [ ] Cloudbeat uses agent config to fetch resources using the mentioned auth methods.

**Related tasks/epics**
Reference related issues and epics
